[package]
name = "stop_it"
version = "0.1.0"
edition = "2024"

[dependencies]
notify-rust = "4.11"
regex = "1.11"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.42", features = ["full"] }
tokio-tungstenite = "0.24"
futures-util = "0.3"
